/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.4.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.savemoney.usermanagement.api.v1;

import com.savemoney.usermanagement.model.v1.CheckIfUserExistsDto;
import com.savemoney.usermanagement.model.v1.CheckIfUserExistsResource;
import com.savemoney.usermanagement.model.v1.NewUserDto;
import com.savemoney.usermanagement.model.v1.NewUserResource;
import com.savemoney.usermanagement.model.v1.UpdateUserDto;
import com.savemoney.usermanagement.model.v1.UpdateUserResource;
import com.savemoney.usermanagement.model.v1.UserResource;
import com.savemoney.usermanagement.model.v1.UsersResource;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-02-13T19:41:36.166055+01:00[Europe/Rome]")
@Validated
@Tag(name = "user-management", description = "the user-management API")
public interface UserManagementApi {

    /**
     * POST /user-management/v1/check-if-user-exists : check if existing an user by id and email
     *
     * @param checkIfUserExistsDto body (optional)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "checkIfUserExists",
        summary = "check if existing an user by id and email",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  CheckIfUserExistsResource.class))),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/user-management/v1/check-if-user-exists",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<CheckIfUserExistsResource> checkIfUserExists(
        @Parameter(name = "CheckIfUserExistsDto", description = "body", schema = @Schema(description = "")) @Valid @RequestBody(required = false) CheckIfUserExistsDto checkIfUserExistsDto
    );


    /**
     * GET /user-management/v1/user/{id}/{details} : get a user by id. If details is set a true, it retrieve userDetail otherwise no
     *
     * @param id  (required)
     * @param details  (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getUserById",
        summary = "get a user by id. If details is set a true, it retrieve userDetail otherwise no",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  UserResource.class))),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/user-management/v1/user/{id}/{details}",
        produces = { "application/json" }
    )
    ResponseEntity<UserResource> getUserById(
        @Parameter(name = "id", description = "", required = true, schema = @Schema(description = "")) @PathVariable("id") Long id,
        @Parameter(name = "details", description = "", required = true, schema = @Schema(description = "")) @PathVariable("details") Boolean details
    );


    /**
     * GET /user-management/v1/users : get a list of user
     *
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "getUsers",
        summary = "get a list of user",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  UsersResource.class))),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/user-management/v1/users",
        produces = { "application/json" }
    )
    ResponseEntity<UsersResource> getUsers(
        
    );


    /**
     * POST /user-management/v1/insert-user : Insert a new user
     *
     * @param newUserDto new user dto (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "insertUser",
        summary = "Insert a new user",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  NewUserResource.class))),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/user-management/v1/insert-user",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<NewUserResource> insertUser(
        @Parameter(name = "NewUserDto", description = "new user dto", required = true, schema = @Schema(description = "")) @Valid @RequestBody NewUserDto newUserDto
    );


    /**
     * PUT /user-management/v1/update-user : update an existing user
     *
     * @param updateUserDto update user dto (required)
     * @return OK (status code 200)
     *         or Created (status code 201)
     *         or Unauthorized (status code 401)
     *         or Forbidden (status code 403)
     *         or Not found (status code 404)
     */
    @Operation(
        operationId = "updateUser",
        summary = "update an existing user",
        responses = {
            @ApiResponse(responseCode = "200", description = "OK", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  UpdateUserResource.class))),
            @ApiResponse(responseCode = "201", description = "Created"),
            @ApiResponse(responseCode = "401", description = "Unauthorized"),
            @ApiResponse(responseCode = "403", description = "Forbidden"),
            @ApiResponse(responseCode = "404", description = "Not found")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/user-management/v1/update-user",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<UpdateUserResource> updateUser(
        @Parameter(name = "UpdateUserDto", description = "update user dto", required = true, schema = @Schema(description = "")) @Valid @RequestBody UpdateUserDto updateUserDto
    );

}
