server:
  port: 8081


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans
  info:
    env:
      enabled: true

info:
  app:
    name: User Management App
    description: A microservice to manage user login
    version: 0.0.1
