server:
  port: 8081
  error:
    include-message: always

spring:
  jpa:
    show-sql: true
#    generate-ddl: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    driver:
      class: org.postgresql.Driver
    driverCLassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user-management
    username: andrew92
    password: Arrudb!92
    initialization-mode: true
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  security:
    user:
      name: pippo
      password: pippo

management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans
  info:
    env:
      enabled: true

info:
  app:
    name: User Management App
    description: A microservice to manage user login
    version: 0.0.1

